module ApplicationHelper
    def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
  def resource_class
    devise_mapping.to
  end

  #for options 
  def get_all_interests
    [
      'Technology',
    'Science',
    'Books',
    'Business',
    'Movies',
    'Health',
    'Visiting and Travel',
    'Music',
    'Education',
    'Food',
    'Psychology',
    'Design',
    'History',
    'Economics',
    'Cooking',
    'Entertainment',
    'Writing',
    'Sports',
    'Photography',
    'Philosophy',
    'Marketing',
    'Finance',
    'Mathematics',
    'Fashion and Style',
    'Politics',
    'Literature',
    'Computer Science',
    'Television Series',
    'Startups',
    'Fine Art',
    'Physics',
    'Entrepreneurship',
    'Google',
    'Journalism',
    'Investing',
    'Healthy Eating',
    'Software Engineering',
    'India',
    'Mobile Phones',
    'Computer Programming',
    'Medicine and Healthcare',
    'Nutrition',
    'Money',
    'Current Events in Technology',
    'Dating and Relationships',
    'Silicon Valley',
    'Writers and Authors',
    'Business Strategy',
    'Novels',
    'Small Businesses'
    ]
  end
  
  def get_all_cities
    [
      
 'Ahmadpur East',
 'Ahmed Nager Chatha',
 'Alipur',
 'Arifwala',
 'Attock',
 'Bhalwal',
 'Bahawalnagar',
 'Bahawalpur',
 'Bhakkar',
 'Burewala',
 'Chillianwala',
 'Chakwal',
 'Chichawatni',
 'Chiniot',
 'Daska',
 'Darya Khan',
 'Dera Ghazi Khan',
 'Dhaular',
 'Dina',
 'Dinga',
 'Dipalpur',
 'Faisalabad',
 'Fateh Jang',
 'Ghakhar Mandi',
 'Gujranwala',
 'Gujrat',
 'Gujar Khan',
 'Hafizabad',
 'Haroonabad',
 'Hasilpur',
 'Haveli Lakha',
 'Jampur',
 'Jhang',
 'Jhelum',
 'Kalabagh',
 'Karor Lal Esan',
 'Kasur',
 'Kamalia',
 'Kāmoke',
 'Khanewal',
 'Khanpur',
 'Kharian',
 'Khushab',
 'Kot Adu',
 'Jauharabad',
 'Lahore',
 'Lalamusa',
 'Layyah',
 'Liaquat Pur',
 'Lodhran',
 'Mamoori',
 'Mandi Bahauddin',
 'Mailsi',
 'Mian Channu',
 'Mianwali',
 'Multan',
 'Murree',
 'Muridke',
 'Muzaffargarh',
 'Narowal',
 'Okara',
 'Renala Khurd',
 'Pakpattan',
 'Pattoki',
 'Pir Mahal',
 'Qila Didar Singh',
 'Rabwah',
 'Raiwind',
 'Rajanpur',
 'Rahim Yar Khan',
 'Rawalpindi',
 'Sadiqabad',
 'Safdarabad',
 'Sahiwal',
 'Sangla Hill',
 'Sarai Alamgir',
 'Sargodha',
 'Shakargarh',
 'Sheikhupura',
 'Sialkot',
 'Sohawa',
 'Soianwala',
 'Talagang',
 'Taxila',
 'Toba Tek Singh',
 'Vehari',
 'Wah Cantonment' ,
 'Wazirabad'
      ]
  end
end
